### PR TITLE
Inversion of words in the description of "grille" mechanism

### PR DESCRIPTION
**Pull request by laem**

### CODE REVIEW

**Review by mquandalle — CHANGES_REQUESTED** [review]
The `mecanisms.json` file is generated from the `mecanisms.yaml` source — it probably shouldn't be committed.

**Comment by laem** [comment]
Oups, of course, sorry.

**Comment by laem** [comment]
I just correct the original yaml too, no time to check if gitignoring the .json doesn't break the docausorus dev experience.

**Comment by mquandalle** [comment]
> no time to check if gitignoring the .json doesn't break the docausorus dev experience.

Ok I'll do it

**Pull request merged**
